### ISSUE TITLE
Backup files can be removed

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy-birds-activity#1]
Editor backup files are in the .xo and the repository; files ending with tilde ~.  These make the bundle larger than it needs to be.

**Comment by davelab6** [comment]
I agree with @quozl that these should be removed :)

**Comment by iamutkarshtiwari** [comment]
@quozl @davelab6 I am unable to find such files in the repository. I am sure that I included those file extensions in the .gitignore.

**Comment by quozl** [comment]
@iamutkarshtiwari, sorry you couldn't find them ... there is an `activity.info~` in flappy_birds-2.xo, which you only just now removed in 92106334e3375420eb0e7a2fb012350c01e61d03.  At time this issue was opened, flappy_birds-1.xo was the latest release, and the files were;

```
score.pkl~
welcomescreen.py~
elements.py~
scorescreen.py~
activity
main.py~
```

Your `.gitignore` could be simplified to `*~`

Also remember to use a pristine or cleaned clone to create the bundle.  Because `.gitignore` is not used by `python setup.py dist_xo`.
