### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy-birds-activity#12]
Distributions are deprecating GTK+ 2, so for the activity to survive it must be ported.

**Comment by iamutkarshtiwari** [comment]
https://github.com/sugarlabs/flappy-birds-activity/commit/3fe6380493c36481a097b2c84e72b4a91e914dad

**Comment by yell0wfl4sh** [comment]
e92ccc9ef100452d37a246b8305db3f128c22a9f This issue can now be closed.
