### ISSUE TITLE
Gtk widget: CSS error

### ISSUE THREAD

**Issue by hv7214** [sugarlabs/flappy-birds-activity#17]
### (sugar-activity:32549): Gtk-WARNING **: 10:34:33.250: Theme parsing error: gtk-widgets.css:16:32: The style property GtkExpander:expander-size is deprecated and shouldn't be used anymore. It will be removed in a future version

3/4th of the screen is being covered, and pipes are flowing out of the window box.

**Comment by hv7214** [comment]
@quozl have a look here!

**Comment by quozl** [comment]
@hv7214, why me?  Who are you?

https://github.com/sugarlabs/flappy should be used instead, see discussion in https://github.com/sugarlabs/flappy-birds-activity/issues/16 which proposes to delete this repository now that we recognise it is a duplicate.
