### ISSUE TITLE
Font licensing

### ISSUE THREAD

**Issue by quozl** [sugarlabs/flappy-birds-activity#2]
Some of the fonts have names that suggest they are copyright by someone else, and it isn't clear that I have a license to use them after I install your bundle.

Instead, use fonts that have a license that allows their use with GPL you have used in source code.

**Comment by davelab6** [comment]
The good news is that the GPL doesn't extend to fonts used by programs, because the fonts are separate works, and thus the fonts are aggregate distribution (like a livecd) rather than combined (derivative) work with the program. 

The bad news is that these fonts are not licensed for redistribution, and I recommend deleting them ASAP :)

**Comment by leonardcj** [comment]
davelab6 can you suggest appropriate substitute fonts to this GSOC contributor?  Do we have fonts already available in Sugar images that might make it un-necessary to package them with the activity?

**Comment by iamutkarshtiwari** [comment]
@leonardcj Could you please suggest me appropriate subtitute fonts?

**Comment by davelab6** [comment]
From github.com/google/fonts
- replace arial.ttf with Arimo-Regular.ttf and add a LICENSE.Arimo.txt
  file; replace comicsans.ttf with ShortStack-Regular.ttf and add
  LICENSE.ShortStack.txt; rename sans.ttf to ClearSans-Regular.ttf and copy
  the Apache license to LICENSE.ClearSans.txt

https://www.google.com/fonts/specimen/Arimo
https://github.com/google/fonts/blob/master/apache/arimo/LICENSE.txt

https://www.google.com/fonts/specimen/Short+Stack
https://github.com/google/fonts/blob/master/ofl/shortstack/OFL.txt

**Comment by iamutkarshtiwari** [comment]
@davelab6 Thank you :)

**Comment by iamutkarshtiwari** [comment]
fixed.
