### ISSUE TITLE
Merge with flappy activity

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/flappy-birds-activity#30]
I'm proposing we merge this activity with [flappy activity](https://github.com/sugarlabs/flappy) as they're currently same activity with some differences;
- Flappy uses a lot more of the pygame canvas while Flappy bird doesn't.
- Flappy has difficulty levels implemented while Flappy bird doesn't.
- Flappy doesn't use arrow keys for movement while Flappy bird does.

I think we should merge both activities and add the features of both to one so we don't keep two different versions of the same activity.

@quozl @aperezbios @walterbender @srevinsaju thoughts?

**Comment by quozl** [comment]
Agreed.  I've often noted the similarities.

**Comment by srevinsaju** [comment]
Agreed, +1

**Comment by chimosky** [comment]
Thanks! 

@sparshg would you like to work on this?

It'll basically involve transferring commits that exist in flappy birds activity but don't exist in [flappy activity](https://github.com/sugarlabs/flappy) and fixing any bugs that come up.

**Comment by sparshg** [comment]
Sure I will try that after my exams.

**Comment by chimosky** [comment]
> Sure I will try that after my exams.

Thanks!

**Comment by sparshg** [comment]
@chimosky I took a look at the flappy activity, in my opinion flappy bird one is much more closer to the original one, (like the physics, the environment and same feeling as the original one). Meanwhile flappy has very odd physics and rotation mechanics which I didn't find enjoyable. 

>Flappy uses a lot more of the pygame canvas while Flappy bird doesn't.

There are just black boxes drawn around canvas give it a portrait mode look, that can be easily fixed.

> Flappy doesn't use arrow keys for movement while Flappy birds do.

Flappy birds can also be controlled by tap/mouse.

In my opinion we should keep flappy bird activity instead.

**Comment by chimosky** [comment]
> Flappy birds can also be controlled by tap/mouse.

Yes both can be controlled with mouse, the idea was to list the difference that we would merge into either when we do the merge.

> In my opinion we should keep flappy bird activity instead.

Are you saying we should merge [flappy activity](https://github.com/sugarlabs/flappy) into flappy birds - this repo - instead?

**Comment by sparshg** [comment]
> Are you saying we should merge [flappy activity](https://github.com/sugarlabs/flappy) into flappy birds - this repo - instead?

Yes, that seems better to me.

**Comment by chimosky** [comment]
> Yes, that seems better to me.

I'm curious, why does it seem better to you?

**Comment by sparshg** [comment]
I stated that here, 
> I took a look at the flappy activity, in my opinion flappy bird one is much more closer to the original one, (like the physics, the environment and same feeling as the original one). Meanwhile flappy has very odd physics and rotation mechanics which I didn't find enjoyable.

> There are just black boxes drawn around canvas give it a portrait mode look, that can be easily fixed.

Here is what I meant by odd physics:
The velocity in that repo varies linearly (so gravity is not simulated) and rotation is broken in steps.

In this repo: 
- Velocity of the bird here is actually affected by acceleration.
- Rotation of the bird is continuous

**Comment by chimosky** [comment]
> I stated that here,
> 
> > I took a look at the flappy activity, in my opinion flappy bird one is much more closer to the original one, (like the physics, the environment and same feeling as the original one). Meanwhile flappy has very odd physics and rotation mechanics which I didn't find enjoyable.
> 
> > There are just black boxes drawn around canvas give it a portrait mode look, that can be easily fixed.

If you take a look you'll see that this repo seems like a fork of the other one and the other one has older commits not included here which I think are important.

> In this repo:
>
>    Velocity of the bird here is actually affected by acceleration.
>    Rotation of the bird is continuous

These are the things that can be merged when the merge happens which is why this issue is open.

**Comment by sparshg** [comment]
Oh okay, makes sense, I will merge this repo on flappy soon.

**Comment by sparshg** [comment]
> If you take a look you'll see that this repo seems like a fork of the other one and the other one has older commits not included here which I think are important.

I saw the initial commit of this repo is fork of sonic jump activity and is not a fork of flappy. Both repos have very different histories... Am I missing something?

**Comment by chimosky** [comment]
> I saw the initial commit of this repo is fork of sonic jump activity and is not a fork of flappy. Both repos have very different histories... Am I missing something?

Sadly, I don't know how it metamorphosed into what it currently is.

**Comment by Dimi20cen** [comment]
So, should we keep the physics/movement mechanics of the flappy-birds and add difficulty levels and arrow key movements?

Edit: Clarification, while flappy doesn't support movement with the up-arrow key, it does support movement with the space key.

**Comment by Dimi20cen** [comment]
I'm currently working on it, I'm using flappy as base
- Code is MUCH more readable and well structured
- Dispaly is adjustable
- Has difficulty levels already implemented

However flappy-birds
- Has better movement, as [sparshg](https://github.com/sparshg) already said
  1. Visually, the rotation of the bird is continuous, it uses one image and rotates it making it look smoother than flappy, which uses multiple images to simulate rotation.
  2. The velocity of the bird is actually affected by acceleration.
- Has better Welcome and Score screen, by better, I mean visually and in the case of the Welcome screen it's more descriptive

**Comment by chimosky** [comment]
> So, should we keep the physics/movement mechanics of the flappy-birds and add difficulty levels and arrow key movements?
> 

Yes the idea is to merge functionality so if something exists in one and doesn't exist in the other, we'll have to implement it in the other.

**Comment by chimosky** [comment]
> I'm currently working on it, I'm using flappy as base
> 
>     * Code is MUCH more readable and well structured
> 
>     * Dispaly is adjustable
> 
>     * Has difficulty levels already implemented
> 
> 
> However flappy-birds
> 
>     * Has better movement, as [sparshg](https://github.com/sparshg) already said
>       
>       1. Visually, the rotation of the bird is continuous, it uses one image and rotates it making it look smoother than flappy, which uses multiple images to simulate rotation.
>       2. The velocity of the bird is actually affected by acceleration.
> 
>     * Has better Welcome and Score screen, by better, I mean visually and in the case of the Welcome screen it's more descriptive


Whichever one we decide to use - @quozl what'd you think? -, I'm fine with merging flappy with this one and I do agree with your analysis above about code structure.

**Comment by Dimi20cen** [comment]
I completed the changes, but I'm having some challenges in determining the appropriate y-velocity of the bird, especially in the low and middle difficulty. Do you have any suggestions or opinions on the matter?<br>
Tomorrow I'll push a PR, and if something doesn't feel right, we can configure from there.

**Comment by sparshg** [comment]
> I completed the changes, but I'm having some challenges in determining the appropriate y-velocity of the bird, especially in the low and middle difficulty. Do you have any suggestions or opinions on the matter?

The physics shouldn't change for the lower difficulty levels, what problem are you facing exactly?
Also, it seems like the current implementation of the physics in this repo is unnecessarily complicated.

**Comment by Dimi20cen** [comment]
Indeed, the physics implementation confused memuch more than necessary, but it's very straight forwards and with better variable naming it's not that complicated, plus it's interesting and gives a bit more flavor to the game. <br>
Anyways, I don't face any specific problem, I'm just trying to decide what's the best velocity and what's the most suitable changing rate of velocity for each level.<br>
I thought that maybe someone had an insight on something that I hadn't even thought on how to choose the optimal motion rate of the bird for each difficulty.

**Comment by sparshg** [comment]
> I'm just trying to decide what's the best velocity and what's the most suitable changing rate of velocity for each level.

Instead of changing rate of velocity, that is gravity, we should vary the speed of incoming pipes to vary the difficulty. (which is already implemented in this repo I think)

**Comment by Dimi20cen** [comment]
By this repo you probably mean flappy, right?

Yes varying the speed of incoming pipes to simulate x-velocity of the bird is already implement in flappy's repo. I don't plan to change that at all, I'm more interested in configuring the y-velocity together with gravity.

**Comment by chimosky** [comment]
> I completed the changes, but I'm having some challenges in determining the appropriate y-velocity of the bird, especially in the low and middle difficulty. Do you have any suggestions or opinions on the matter? Tomorrow I'll push a PR, and if something doesn't feel right, we can configure from there.

Waiting to see a PR.

> By this repo you probably mean flappy, right?

This repo is flappy birds.

**Comment by Dimi20cen** [comment]
Yep, I did a PR, but I did it in the flappy’s repo, since I used it as base. Would it be better to PR in this repo instead?

**Comment by chimosky** [comment]
In the chats above there's mention of merging with this but we don't seem to have consensus on it as @quozl hasn't said anything about that but I'm fine with using this one as a base.

**Comment by chimosky** [comment]
After the merge is done, does everyone agree to deleting this repo or we can leave it here but remove all the files.

@quozl @srevinsaju @sparshg @Dimi20cen

**Comment by Dimi20cen** [comment]
Would archiving it be a valid choice?

**Comment by quozl** [comment]
This hasn't really come up before.  Mostly people don't write new activities that duplicate another one, they stay well enough away.  Such antisocial behaviour needs to be reigned in.  :grin:  Best fit with our conventions would be to merge the new repository into this one, replacing all the files so that clones would look identical apart from history, then a commit that removes all the files leaving a pointer to the replacement activity.  Otherwise someone later may take a release .xo file and say "hey, it's not on GitHub, let's create a repository".

**Comment by chimosky** [comment]
> This hasn't really come up before. Mostly people don't write new activities that duplicate another one, they stay well enough away. Such antisocial behaviour needs to be reigned in. 😁 Best fit with our conventions would be to merge the new repository into this one, replacing all the files so that clones would look identical apart from history, then a commit that removes all the files leaving a pointer to the replacement activity. Otherwise someone later may take a release .xo file and say "hey, it's not on GitHub, let's create a repository".

Opened #32, kindly review.

**Comment by quozl** [comment]
Last step?  Check the open issues and work them to closure.

**Comment by quozl** [comment]
A README.md that points at the new repository would be helpful.

**Comment by Dimi20cen** [comment]
Opened #33 for README.md

**Comment by Dimi20cen** [comment]
> Last step? Check the open issues and work them to closure.

Do you mean that the open issues need to be resolved? Or just closed?

**Comment by quozl** [comment]
I'm surprised you ask.  They need to be checked to see if they persist in the new activity, then either moved to the new repository, fixed, or closed, depending on decision of developer.

**Comment by chimosky** [comment]
> Last step? Check the open issues and work them to closure.

I'll transfer all open issues and indicate that they were transferred so people should try reproducing first.

**Comment by Dimi20cen** [comment]
>I'm surprised you ask. They need to be checked to see if they persist in the new activity, then either moved to the new repository, fixed, or closed, depending on decision of developer.

Hahahah, sometimes I even surprise myself with my questions. However, I used flappy's code as the base for the merge and while I implemented some concepts from flappy-bird-activity, I didn't use any of it's code.
