### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [sugarlabs/flappy-birds-activity#6]
Please :)

**Comment by iamutkarshtiwari** [comment]
@davelab6 Could you please guide me for the same?

**Comment by davelab6** [comment]
Please see https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub :) 

The transfer option is in https://github.com/iamutkarshtiwari/Flappy-Birds/settings

**Comment by iamutkarshtiwari** [comment]
@davelab6 Will do it ASAP.

**Comment by iamutkarshtiwari** [comment]
@davelab6 I have other 5 activities on Sugar. Shall I move them as well or just this one?

**Comment by davelab6** [comment]
Please do! :)

On 25 May 2016 at 15:18, Utkarsh Tiwari notifications@github.com wrote:

> @davelab6 https://github.com/davelab6 I have other 5 activities on
> Sugar. Shall I move them as well?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/iamutkarshtiwari/Flappy-Birds/issues/6#issuecomment-221678482

## 

Cheers
Dave

**Comment by iamutkarshtiwari** [comment]
done :+1:
